### ISSUE TITLE
Editor 6.3.0-alpha1 - larger files performance 

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#200]
Hi,

Noticed that handling larger files (300+ lines) is very slow, (10+ sec for opening, 30+ sec for editing, committing), the Editor even hangs/become non-responsive couple of times, when performing operations on them.

Tested with AsciiDoc and JS files, not sure about MarkDown. Maybe connected to #197?

Windows 7 Pro, 64-bit

Thanks,
Imre

**Comment by SamyPesse** [comment]
We just released the first beta of 6.3.0, you can download it and read the full changelog at [gitbook.com/editor/releases/all](https://www.gitbook.com/editor/releases/all).

Can you test the latest beta and tell us if you see improvements ?

**Comment by KINGSABRI** [comment]
Getting the following error when open a big document

![selection_073](https://cloud.githubusercontent.com/assets/1071827/20427602/dcd8c72a-ad95-11e6-9edf-cc110549b560.png)

**Comment by AaronO** [comment]
@KINGSABRI Thanks for testing.

Could you paste the actual text of those error messages here ? (easier to debug)

**Comment by nagim** [comment]
Editing performance is much improved, I haven't encountered lags.

But when opening a really long summary or glossary (500-1000) lines, the Editor can still hang for ~30 seconds before opening.

**Comment by KINGSABRI** [comment]
It doesn't allow text copy! So I copied it via DeveTools

```
Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60LangSelector%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

```
Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=ButtonGroup for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by nagim** [comment]
Tested with 6.3.0-beta3 and the performance is now good, thanks a lot! :+1: 

I wait for @KINGSABRI to verify if his issue still persist before closing this.

**Comment by KINGSABRI** [comment]
@nagim it's a little bit faster, but not good to me, it takes about 15 second to open everything of my book

**Comment by nagim** [comment]
@KINGSABRI It was improved in 6.3.0, but yes, recently, there has been a degradation in performance again (although it's not as slow as it was at the beginning).

**Comment by KINGSABRI** [comment]
@nagim that's right, I just tested it on `v6. 4.2` still slow, actually it takes more than 20 seconds

**Comment by Soreine** [comment]
Opened https://github.com/GitbookIO/feedback/issues/281
