### ISSUE TITLE
Unable to copy into clipboard

### ISSUE THREAD

**Issue by zdne** [GitbookIO/feedback#373]
## Category

Bug

Basic editing functionality doesn't work. 

## What is the current behavior?

A text cannot be copied using CMD+C (Or CMD+X)

## What is the desired behavior?

A text can be copied into clipboard using CMD +C (Or CMD+X)

## Additional information

- macOS Sierra 10.12.3 (16D32)
- Safari Version 10.0.3 (12602.4.8)

This happens both in Markdown and Ritch text editor.

**Comment by SamyPesse** [comment]
What version of the editor are you using ? This bug should have been fixed in `7.0.3`.

Ensure that you are running the latest version:

<img width="322" alt="screen shot 2017-02-20 at 10 01 40" src="https://cloud.githubusercontent.com/assets/845425/23118216/a0c30a40-f753-11e6-81d5-cfa29ad2e72a.png">

**Comment by zdne** [comment]
@SamyPesse Hey, this is in Safari no the GitBook editor

**Comment by SamyPesse** [comment]
Ok thanks, I'm going to investigate the bug and release a fix.

**Comment by zdne** [comment]
@SamyPesse thanks! Let me know should you need more details.

**Comment by zdne** [comment]
Is this tracked somewhere else? The bug still persists. I'm unable to copy and paste in Safari.

**Comment by SamyPesse** [comment]
Yes, we are releasing the version 7.0.4 that fixes it.

It'll be deployed in less than 15minutes.

**Comment by SamyPesse** [comment]
A commit closed this issue automatically:

<img width="806" alt="screen shot 2017-02-22 at 10 59 08" src="https://cloud.githubusercontent.com/assets/845425/23206452/fd64c6e4-f8ed-11e6-95ac-32e60290b570.png">
